<?php

namespace Kanunak\Money;

use JimmyOak\DataType\Enum;

class Currency extends Enum
{
    const CURRENCY_CODE_EURO = 'EUR';
    const CURRENCY_CODE_US_DOLLAR = 'USD';
    const CURRENCY_CODE_BRITISH_POUND = 'GBP';

    const CURRENCY_CODE_UNITED_ARAB_EMIRATES_DIRHAM = 'AED';
    const CURRENCY_CODE_AFGHANISTAN_AFGHANI = 'AFN';
    const CURRENCY_CODE_ALBANIA_LEK = 'ALL';
    const CURRENCY_CODE_ARMENIA_DRAM = 'AMD';
    const CURRENCY_CODE_NETHERLANDS_ANTILLES_GUILDER = 'ANG';
    const CURRENCY_CODE_ANGOLA_KWANZA = 'AOA';
    const CURRENCY_CODE_ARGENTINA_PESO = 'ARS';
    const CURRENCY_CODE_AUSTRALIA_DOLLAR = 'AUD';
    const CURRENCY_CODE_ARUBA_GUILDER = 'AWG';
    const CURRENCY_CODE_AZERBAIJAN_NEW_MANAT = 'AZN';
    const CURRENCY_CODE_BOSNIA_AND_HERZEGOVINA_CONVERTIBLE_MARKA = 'BAM';
    const CURRENCY_CODE_BARBADOS_DOLLAR = 'BBD';
    const CURRENCY_CODE_BANGLADESH_TAKA = 'BDT';
    const CURRENCY_CODE_BULGARIA_LEV = 'BGN';
    const CURRENCY_CODE_BAHRAIN_DINAR = 'BHD';
    const CURRENCY_CODE_BURUNDI_FRANC = 'BIF';
    const CURRENCY_CODE_BERMUDA_DOLLAR = 'BMD';
    const CURRENCY_CODE_BRUNEI_DARUSSALAM_DOLLAR = 'BND';
    const CURRENCY_CODE_BOLIVIA_BOLÍVIANO = 'BOB';
    const CURRENCY_CODE_BRAZIL_REAL = 'BRL';
    const CURRENCY_CODE_BAHAMAS_DOLLAR = 'BSD';
    const CURRENCY_CODE_BHUTAN_NGULTRUM = 'BTN';
    const CURRENCY_CODE_BOTSWANA_PULA = 'BWP';
    const CURRENCY_CODE_BELARUS_RUBLE = 'BYR';
    const CURRENCY_CODE_BELIZE_DOLLAR = 'BZD';
    const CURRENCY_CODE_CANADA_DOLLAR = 'CAD';
    const CURRENCY_CODE_CONGO_KINSHASA_FRANC = 'CDF';
    const CURRENCY_CODE_SWITZERLAND_FRANC = 'CHF';
    const CURRENCY_CODE_CHILE_PESO = 'CLP';
    const CURRENCY_CODE_CHINA_YUAN_RENMINBI = 'CNY';
    const CURRENCY_CODE_COLOMBIA_PESO = 'COP';
    const CURRENCY_CODE_COSTA_RICA_COLON = 'CRC';
    const CURRENCY_CODE_CUBA_CONVERTIBLE_PESO = 'CUC';
    const CURRENCY_CODE_CUBA_PESO = 'CUP';
    const CURRENCY_CODE_CAPE_VERDE_ESCUDO = 'CVE';
    const CURRENCY_CODE_CZECH_REPUBLIC_KORUNA = 'CZK';
    const CURRENCY_CODE_DJIBOUTI_FRANC = 'DJF';
    const CURRENCY_CODE_DENMARK_KRONE = 'DKK';
    const CURRENCY_CODE_DOMINICAN_REPUBLIC_PESO = 'DOP';
    const CURRENCY_CODE_ALGERIA_DINAR = 'DZD';
    const CURRENCY_CODE_EGYPT_POUND = 'EGP';
    const CURRENCY_CODE_ERITREA_NAKFA = 'ERN';
    const CURRENCY_CODE_ETHIOPIA_BIRR = 'ETB';
    const CURRENCY_CODE_EURO_MEMBER_COUNTRIES = 'EUR';
    const CURRENCY_CODE_FIJI_DOLLAR = 'FJD';
    const CURRENCY_CODE_FALKLAND_ISLANDS_MALVINAS_POUND = 'FKP';
    const CURRENCY_CODE_UNITED_KINGDOM_POUND = 'GBP';
    const CURRENCY_CODE_GEORGIA_LARI = 'GEL';
    const CURRENCY_CODE_GUERNSEY_POUND = 'GGP';
    const CURRENCY_CODE_GHANA_CEDI = 'GHS';
    const CURRENCY_CODE_GIBRALTAR_POUND = 'GIP';
    const CURRENCY_CODE_GAMBIA_DALASI = 'GMD';
    const CURRENCY_CODE_GUINEA_FRANC = 'GNF';
    const CURRENCY_CODE_GUATEMALA_QUETZAL = 'GTQ';
    const CURRENCY_CODE_GUYANA_DOLLAR = 'GYD';
    const CURRENCY_CODE_HONG_KONG_DOLLAR = 'HKD';
    const CURRENCY_CODE_HONDURAS_LEMPIRA = 'HNL';
    const CURRENCY_CODE_CROATIA_KUNA = 'HRK';
    const CURRENCY_CODE_HAITI_GOURDE = 'HTG';
    const CURRENCY_CODE_HUNGARY_FORINT = 'HUF';
    const CURRENCY_CODE_INDONESIA_RUPIAH = 'IDR';
    const CURRENCY_CODE_ISRAEL_SHEKEL = 'ILS';
    const CURRENCY_CODE_ISLE_OF_MAN_POUND = 'IMP';
    const CURRENCY_CODE_INDIA_RUPEE = 'INR';
    const CURRENCY_CODE_IRAQ_DINAR = 'IQD';
    const CURRENCY_CODE_IRAN_RIAL = 'IRR';
    const CURRENCY_CODE_ICELAND_KRONA = 'ISK';
    const CURRENCY_CODE_JERSEY_POUND = 'JEP';
    const CURRENCY_CODE_JAMAICA_DOLLAR = 'JMD';
    const CURRENCY_CODE_JORDAN_DINAR = 'JOD';
    const CURRENCY_CODE_JAPAN_YEN = 'JPY';
    const CURRENCY_CODE_KENYA_SHILLING = 'KES';
    const CURRENCY_CODE_KYRGYZSTAN_SOM = 'KGS';
    const CURRENCY_CODE_CAMBODIA_RIEL = 'KHR';
    const CURRENCY_CODE_COMOROS_FRANC = 'KMF';
    const CURRENCY_CODE_KOREA_NORTH_WON = 'KPW';
    const CURRENCY_CODE_KOREA_SOUTH_WON = 'KRW';
    const CURRENCY_CODE_KUWAIT_DINAR = 'KWD';
    const CURRENCY_CODE_CAYMAN_ISLANDS_DOLLAR = 'KYD';
    const CURRENCY_CODE_KAZAKHSTAN_TENGE = 'KZT';
    const CURRENCY_CODE_LAOS_KIP = 'LAK';
    const CURRENCY_CODE_LEBANON_POUND = 'LBP';
    const CURRENCY_CODE_SRI_LANKA_RUPEE = 'LKR';
    const CURRENCY_CODE_LIBERIA_DOLLAR = 'LRD';
    const CURRENCY_CODE_LESOTHO_LOTI = 'LSL';
    const CURRENCY_CODE_LIBYA_DINAR = 'LYD';
    const CURRENCY_CODE_MOROCCO_DIRHAM = 'MAD';
    const CURRENCY_CODE_MOLDOVA_LEU = 'MDL';
    const CURRENCY_CODE_MADAGASCAR_ARIARY = 'MGA';
    const CURRENCY_CODE_MACEDONIA_DENAR = 'MKD';
    const CURRENCY_CODE_MYANMAR_BURMA_KYAT = 'MMK';
    const CURRENCY_CODE_MONGOLIA_TUGHRIK = 'MNT';
    const CURRENCY_CODE_MACAU_PATACA = 'MOP';
    const CURRENCY_CODE_MAURITANIA_OUGUIYA = 'MRO';
    const CURRENCY_CODE_MAURITIUS_RUPEE = 'MUR';
    const CURRENCY_CODE_MALDIVES_RUFIYAA = 'MVR';
    const CURRENCY_CODE_MALAWI_KWACHA = 'MWK';
    const CURRENCY_CODE_MEXICO_PESO = 'MXN';
    const CURRENCY_CODE_MALAYSIA_RINGGIT = 'MYR';
    const CURRENCY_CODE_MOZAMBIQUE_METICAL = 'MZN';
    const CURRENCY_CODE_NAMIBIA_DOLLAR = 'NAD';
    const CURRENCY_CODE_NIGERIA_NAIRA = 'NGN';
    const CURRENCY_CODE_NICARAGUA_CORDOBA = 'NIO';
    const CURRENCY_CODE_NORWAY_KRONE = 'NOK';
    const CURRENCY_CODE_NEPAL_RUPEE = 'NPR';
    const CURRENCY_CODE_NEW_ZEALAND_DOLLAR = 'NZD';
    const CURRENCY_CODE_OMAN_RIAL = 'OMR';
    const CURRENCY_CODE_PANAMA_BALBOA = 'PAB';
    const CURRENCY_CODE_PERU_SOL = 'PEN';
    const CURRENCY_CODE_PAPUA_NEW_GUINEA_KINA = 'PGK';
    const CURRENCY_CODE_PHILIPPINES_PESO = 'PHP';
    const CURRENCY_CODE_PAKISTAN_RUPEE = 'PKR';
    const CURRENCY_CODE_POLAND_ZLOTY = 'PLN';
    const CURRENCY_CODE_PARAGUAY_GUARANI = 'PYG';
    const CURRENCY_CODE_QATAR_RIYAL = 'QAR';
    const CURRENCY_CODE_ROMANIA_NEW_LEU = 'RON';
    const CURRENCY_CODE_SERBIA_DINAR = 'RSD';
    const CURRENCY_CODE_RUSSIA_RUBLE = 'RUB';
    const CURRENCY_CODE_RWANDA_FRANC = 'RWF';
    const CURRENCY_CODE_SAUDI_ARABIA_RIYAL = 'SAR';
    const CURRENCY_CODE_SOLOMON_ISLANDS_DOLLAR = 'SBD';
    const CURRENCY_CODE_SEYCHELLES_RUPEE = 'SCR';
    const CURRENCY_CODE_SUDAN_POUND = 'SDG';
    const CURRENCY_CODE_SWEDEN_KRONA = 'SEK';
    const CURRENCY_CODE_SINGAPORE_DOLLAR = 'SGD';
    const CURRENCY_CODE_SAINT_HELENA_POUND = 'SHP';
    const CURRENCY_CODE_SIERRA_LEONE_LEONE = 'SLL';
    const CURRENCY_CODE_SOMALIA_SHILLING = 'SOS';
    const CURRENCY_CODE_SEBORGA_LUIGINO = 'SPL*';
    const CURRENCY_CODE_SURINAME_DOLLAR = 'SRD';
    const CURRENCY_CODE_SAO_TOME_AND_PRINCIPE_DOBRA = 'STD';
    const CURRENCY_CODE_EL_SALVADOR_COLON = 'SVC';
    const CURRENCY_CODE_SYRIA_POUND = 'SYP';
    const CURRENCY_CODE_SWAZILAND_LILANGENI = 'SZL';
    const CURRENCY_CODE_THAILAND_BAHT = 'THB';
    const CURRENCY_CODE_TAJIKISTAN_SOMONI = 'TJS';
    const CURRENCY_CODE_TURKMENISTAN_MANAT = 'TMT';
    const CURRENCY_CODE_TUNISIA_DINAR = 'TND';
    const CURRENCY_CODE_TONGA_PA_ANGA = 'TOP';
    const CURRENCY_CODE_TURKEY_LIRA = 'TRY';
    const CURRENCY_CODE_TRINIDAD_AND_TOBAGO_DOLLAR = 'TTD';
    const CURRENCY_CODE_TUVALU_DOLLAR = 'TVD';
    const CURRENCY_CODE_TAIWAN_NEW_DOLLAR = 'TWD';
    const CURRENCY_CODE_TANZANIA_SHILLING = 'TZS';
    const CURRENCY_CODE_UKRAINE_HRYVNIA = 'UAH';
    const CURRENCY_CODE_UGANDA_SHILLING = 'UGX';
    const CURRENCY_CODE_UNITED_STATES_DOLLAR = 'USD';
    const CURRENCY_CODE_URUGUAY_PESO = 'UYU';
    const CURRENCY_CODE_UZBEKISTAN_SOM = 'UZS';
    const CURRENCY_CODE_VENEZUELA_BOLIVAR = 'VEF';
    const CURRENCY_CODE_VIET_NAM_DONG = 'VND';
    const CURRENCY_CODE_VANUATU_VATU = 'VUV';
    const CURRENCY_CODE_SAMOA_TALA = 'WST';
    const CURRENCY_CODE_COMMUNAUTE_FINANCIERE_AFRICAINE_BEAC_CFA_FRANC_BEAC = 'XAF';
    const CURRENCY_CODE_EAST_CARIBBEAN_DOLLAR = 'XCD';
    const CURRENCY_CODE_INTERNATIONAL_MONETARY_FUND_IMF_SPECIAL_DRAWING_RIGHTS = 'XDR';
    const CURRENCY_CODE_COMMUNAUTE_FINANCIERE_AFRICAINE_BCEAO_FRANC = 'XOF';
    const CURRENCY_CODE_COMPTOIRS_FRANCAIS_DU_PACIFIQUE_CFP_FRANC = 'XPF';
    const CURRENCY_CODE_YEMEN_RIAL = 'YER';
    const CURRENCY_CODE_SOUTH_AFRICA_RAND = 'ZAR';
    const CURRENCY_CODE_ZAMBIA_KWACHA = 'ZMW';
    const CURRENCY_CODE_ZIMBABWE_DOLLAR = 'ZWD';

    /**
     * @param string $currencyCode
     */
    public function __construct($currencyCode)
    {
        parent::__construct($currencyCode);
    }

    /**
     * @return string
     */
    public function code()
    {
        return $this->value();
    }

    /**
     * @return string[]
     */
    public static function availableCurrencyCodes()
    {
        return self::getConstList();
    }
}
